### ISSUE TITLE
link with umlauts 

### ISSUE THREAD

**Issue by Jan-Rueter** [floorish/smooth-scroll#2]
markdown-parser automatically generates IDs of a headline´s text, 

problem if the headline contains umlauts ( äöüÄÖÜ )

markdown: ### Wurst und Käse

generated: <h3 id="wurst-und-käse">Wurst und Käse</h3>

the link: <a href="#wurst-und-käse">Wurst und Käse</a>

hoovering the link displays it encoded in the status bar of the browser, 
the link works fine, but not with smooth-scroll

**Comment by floorish** [comment]
Thanks for the feedback, will take a look at it

**Comment by Jan-Rueter** [comment]
Ah, thank you for the message
